name: SCAPE Map Reduce Tool wrapper
vendor: SCAPE        
maintainer:
  name: Rainer Schmidt
  email: rainer( DOT )schmidt( AT )ait( DOT )ac( DOT )at
  name: Matthias Rella
  email: matthias( DOT )rella( DOT )fl( AT )ait( DOT )ac( DOT )at
